name: related
description: Generate related posts
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
    sdk: ^3.0.6

# Add regular dependencies here.
dependencies:

dev_dependencies:
    lints: ^2.0.0
